# Generated by Django 6.0.7 on 2026-07-18 00:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0012_studentprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('credit_hours', models.PositiveSmallIntegerField()),
                ('level', models.PositiveSmallIntegerField(help_text='100, 200, 300, 400, etc.')),
                ('semester', models.CharField(choices=[('FIRST', 'First Semester'), ('SECOND', 'Second Semester'), ('SUMMER', 'Summer')], max_length=10)),
                ('is_core', models.BooleanField(default=True, help_text='Required course or elective')),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='admissions.department')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='admissions.programme')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['level', 'code'],
            },
        ),
    ]
