# Generated by Django 6.0.7 on 2026-07-18 01:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0012_studentprofile'),
        ('courses', '0002_courseprerequisite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammeCurriculum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.PositiveSmallIntegerField(help_text='100, 200, 300, 400, etc.')),
                ('semester', models.CharField(choices=[('FIRST', 'First Semester'), ('SECOND', 'Second Semester'), ('SUMMER', 'Summer')], max_length=10)),
                ('is_required', models.BooleanField(default=True, help_text='Required or elective course')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curricula', to='courses.course')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum', to='admissions.programme')),
            ],
            options={
                'verbose_name': 'Programme Curriculum',
                'verbose_name_plural': 'Programme Curricula',
                'ordering': ['programme', 'level', 'semester', 'course__code'],
                'constraints': [models.UniqueConstraint(fields=('programme', 'course'), name='unique_programme_course')],
            },
        ),
    ]
