# Generated by Django 6.0.7 on 2026-07-18 01:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0012_studentprofile'),
        ('courses', '0003_programmecurriculum'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maximum_students', models.PositiveIntegerField(default=100)),
                ('registration_open', models.DateField()),
                ('registration_close', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_offerings', to='admissions.academicsession')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='courses.course')),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_offerings', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_offerings', to='admissions.semester')),
            ],
            options={
                'verbose_name': 'Course Offering',
                'verbose_name_plural': 'Course Offerings',
                'ordering': ['course__code'],
                'constraints': [models.UniqueConstraint(fields=('course', 'academic_session', 'semester'), name='unique_course_offering')],
            },
        ),
    ]
