# Generated by Django 6.0.7 on 2026-07-18 01:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0012_studentprofile'),
        ('courses', '0004_courseoffering'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DROPPED', 'Dropped'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='courses.courseoffering')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_registrations', to='admissions.enrollment')),
            ],
            options={
                'verbose_name': 'Course Registration',
                'verbose_name_plural': 'Course Registrations',
                'ordering': ['-registered_at'],
                'constraints': [models.UniqueConstraint(fields=('enrollment', 'course_offering'), name='unique_course_registration')],
            },
        ),
    ]
