# Generated by Django 6.0.7 on 2026-07-18 02:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_assessmenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('total_marks', models.DecimalField(decimal_places=2, default=100.0, max_digits=6)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Percentage contribution to final grade', max_digits=5)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('assessment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='courses.assessmenttype')),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='courses.courseoffering')),
            ],
            options={
                'verbose_name': 'Assessment',
                'verbose_name_plural': 'Assessments',
                'ordering': ['course_offering', 'due_date'],
                'constraints': [models.UniqueConstraint(fields=('course_offering', 'title'), name='unique_assessment_title_per_course_offering')],
            },
        ),
    ]
