# Generated by Django 6.0.7 on 2026-07-18 02:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_assessment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_absent', models.BooleanField(default=False)),
                ('feedback', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assessments', to='courses.assessment')),
                ('course_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='courses.courseregistration')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Assessment',
                'verbose_name_plural': 'Student Assessments',
                'ordering': ['assessment', 'course_registration'],
                'constraints': [models.UniqueConstraint(fields=('assessment', 'course_registration'), name='unique_student_assessment')],
            },
        ),
    ]
