# Generated by Django 6.0.7 on 2026-07-18 02:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_studentassessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalGrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('final_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('letter_grade', models.CharField(choices=[('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=2)),
                ('grade_point', models.DecimalField(decimal_places=2, max_digits=3)),
                ('is_passed', models.BooleanField(default=True)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('course_registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_grade', to='courses.courseregistration')),
            ],
            options={
                'verbose_name': 'Final Grade',
                'verbose_name_plural': 'Final Grades',
                'ordering': ['course_registration'],
            },
        ),
    ]
