# Generated by Django 6.0.7 on 2026-07-18 02:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_finalgrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('letter_grade', models.CharField(max_length=5, unique=True)),
                ('minimum_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('maximum_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade_point', models.DecimalField(decimal_places=2, max_digits=3)),
                ('remarks', models.CharField(blank=True, max_length=100)),
                ('is_pass', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Grade Scale',
                'verbose_name_plural': 'Grade Scales',
                'ordering': ['-minimum_score'],
            },
        ),
    ]
