# Generated by Django 6.0.7 on 2026-07-18 02:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0012_studentprofile'),
        ('courses', '0010_gradescale'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_credit_hours', models.PositiveIntegerField(default=0)),
                ('earned_credit_hours', models.PositiveIntegerField(default=0)),
                ('total_grade_points', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('semester_gpa', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('cumulative_gpa', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('academic_standing', models.CharField(choices=[('GOOD', 'Good Standing'), ('PROBATION', 'Academic Probation'), ('SUSPENSION', 'Academic Suspension')], default='GOOD', max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_records', to='admissions.academicsession')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_records', to='admissions.enrollment')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_records', to='admissions.semester')),
            ],
            options={
                'verbose_name': 'Academic Record',
                'verbose_name_plural': 'Academic Records',
                'ordering': ['enrollment', '-academic_session', '-semester'],
                'constraints': [models.UniqueConstraint(fields=('enrollment', 'academic_session', 'semester'), name='unique_academic_record')],
            },
        ),
    ]
