# Generated by Django 6.0.7 on 2026-07-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_course_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_core',
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('CORE', 'Core'), ('ELECTIVE', 'Elective')], default='CORE', max_length=20),
        ),
        migrations.AlterField(
            model_name='programmecurriculum',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(100, '100 Level'), (200, '200 Level'), (300, '300 Level'), (400, '400 Level'), (500, '500 Level')]),
        ),
    ]
