# Generated by Django 6.0.7 on 2026-08-04 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0016_alter_studentprofile_blood_group_and_more'),
        ('courses', '0013_remove_course_is_core_course_course_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistration',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_registrations', to='admissions.enrollment'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['programme'], name='courses_cou_program_a1a486_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['department'], name='courses_cou_departm_93b58f_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['level'], name='courses_cou_level_bf0a39_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['semester'], name='courses_cou_semeste_2d692f_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_type'], name='courses_cou_course__cb41c9_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_active'], name='courses_cou_is_acti_3c7e41_idx'),
        ),
    ]
