# Generated by Django 6.0.7 on 2026-07-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
