# Generated by Django 6.0.7 on 2026-07-17 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_programme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='award',
            field=models.CharField(help_text='Example: Certificate, Diploma, BSc, BA, BEng, MSc, MBA', max_length=50),
        ),
    ]
