# Generated by Django 6.0.7 on 2026-07-17 18:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0008_studentapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('PASSPORT', 'Passport Photograph'), ('NATIONAL_ID', 'National ID'), ('BIRTH_CERTIFICATE', 'Birth Certificate'), ('WASSCE', 'WASSCE/WAEC Result'), ('TRANSCRIPT', 'Academic Transcript'), ('RECOMMENDATION', 'Recommendation Letter'), ('OTHER', 'Other')], max_length=30)),
                ('file', models.FileField(upload_to='applications/documents/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admissions.studentapplication')),
            ],
            options={
                'verbose_name': 'Application Document',
                'verbose_name_plural': 'Application Documents',
                'ordering': ['document_type'],
            },
        ),
    ]
