# Generated by Django 6.0.7 on 2026-07-17 23:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0009_applicationdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WAITLISTED', 'Waitlisted'), ('DEFERRED', 'Deferred')], max_length=20)),
                ('review_comments', models.TextField(blank=True)),
                ('decision_date', models.DateTimeField(auto_now_add=True)),
                ('offer_letter_generated', models.BooleanField(default=False)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='admissions.studentapplication')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admission Decision',
                'verbose_name_plural': 'Admission Decisions',
                'ordering': ['-decision_date'],
            },
        ),
    ]
