# Generated by Django 6.0.7 on 2026-07-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0013_alter_department_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student_id',
            field=models.CharField(db_index=True, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='code',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='code',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='application_number',
            field=models.CharField(db_index=True, editable=False, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='national_id_number',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
