# Generated by Django 6.0.7 on 2026-07-24 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0014_alter_department_code_alter_enrollment_student_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='is_active',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DEFERRED', 'Deferred'), ('SUSPENDED', 'Suspended'), ('WITHDRAWN', 'Withdrawn'), ('GRADUATED', 'Graduated')], default='ACTIVE', max_length=20),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['programme'], name='admissions__program_9eecc7_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['academic_session'], name='admissions__academi_457b26_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['semester'], name='admissions__semeste_b2331a_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['status'], name='admissions__status_9943cc_idx'),
        ),
    ]
