# Generated by Django 6.0.7 on 2026-07-25 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0015_remove_enrollment_is_active_enrollment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='emergency_contact_phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?[0-9]{7,15}$')]),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='guardian_phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?[0-9]{7,15}$')]),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='passport_number',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['marital_status'], name='admissions__marital_70c5ac_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['passport_number'], name='admissions__passpor_a5a18b_idx'),
        ),
    ]
